"""Linux OS adapter (Hyprland + PipeWire + playerctl).

All shell commands are hard-coded here, never generated by the decision layer.
The subprocess runner is injectable so tests exercise dispatch without touching
the real machine.
"""

from __future__ import annotations

import subprocess
from typing import Callable

from controller.actions.registry import LINUX
from controller.decision.schemas import Intent
from controller.os.base import ExecutionResult, OSController

# A runner takes an argv list and returns (returncode, stderr_text).
Runner = Callable[[list[str]], "tuple[int, str]"]


def _subprocess_runner(argv: list[str]) -> tuple[int, str]:
    proc = subprocess.run(argv, capture_output=True, text=True)
    return proc.returncode, proc.stderr.strip()


def _search_url(query: str, engine: str) -> str:
    from urllib.parse import quote_plus

    q = quote_plus(query)
    if engine == "youtube":
        return f"https://www.youtube.com/results?search_query={q}"
    return f"https://www.google.com/search?q={q}"


def _normalize_url(url: str) -> str:
    return url if url.startswith(("http://", "https://")) else f"https://{url}"


class LinuxController(OSController):
    platform = LINUX

    def __init__(self, runner: Runner | None = None):
        self._run = runner or _subprocess_runner
        # action -> handler(params) -> argv. Only actions present here are
        # supported by this adapter; the rest report "unsupported".
        self._handlers: dict[str, Callable[[dict], list[str]]] = {
            "open_app": lambda p: ["hyprctl", "dispatch", "exec", p["application"]],
            "switch_workspace": lambda p: ["hyprctl", "dispatch", "workspace", str(p["workspace"])],
            "next_workspace": lambda p: ["hyprctl", "dispatch", "workspace", "+1"],
            "previous_workspace": lambda p: ["hyprctl", "dispatch", "workspace", "-1"],
            "volume_up": lambda p: [
                "wpctl", "set-volume", "@DEFAULT_AUDIO_SINK@", f"{p.get('amount', 5)}%+"
            ],
            "volume_down": lambda p: [
                "wpctl", "set-volume", "@DEFAULT_AUDIO_SINK@", f"{p.get('amount', 5)}%-"
            ],
            "mute": lambda p: ["wpctl", "set-mute", "@DEFAULT_AUDIO_SINK@", "toggle"],
            "play_pause": lambda p: ["playerctl", "play-pause"],
            "next_track": lambda p: ["playerctl", "next"],
            "previous_track": lambda p: ["playerctl", "previous"],
            "lock_screen": lambda p: ["loginctl", "lock-session"],
            "close_app": lambda p: ["hyprctl", "dispatch", "killactive"],
            "focus_window": lambda p: ["hyprctl", "dispatch", "cyclenext"],
            "move_window": lambda p: [
                # swapwindow visibly swaps with the tiled neighbor; movewindow
                # silently no-ops in dwindle when there's no space that way.
                "hyprctl", "dispatch", "swapwindow",
                {"left": "l", "right": "r", "up": "u", "down": "d"}[p.get("direction", "right")],
            ],
            "resize_window": lambda p: [
                "hyprctl", "dispatch", "resizeactive",
                *(["100", "100"] if p.get("mode", "grow") == "grow" else ["-100", "-100"]),
            ],
            "web_search": lambda p: ["xdg-open", _search_url(p["query"], p.get("engine", "google"))],
            "open_url": lambda p: ["xdg-open", _normalize_url(p["url"])],
        }

    def execute(self, intent: Intent) -> ExecutionResult:
        handler = self._handlers.get(intent.action)
        if handler is None:
            return ExecutionResult(
                status="unsupported",
                detail=f"'{intent.action}' not implemented in Linux adapter",
            )
        try:
            argv = handler(intent.parameters)
        except KeyError as e:
            return ExecutionResult(status="error", detail=f"missing parameter: {e}")

        code, err = self._run(argv)
        if code == 0:
            return ExecutionResult(status="success", detail=" ".join(argv))
        return ExecutionResult(status="error", detail=err or f"exit code {code}")
